### ISSUE TITLE
Can you add the function of remembering the user name and password?

### ISSUE THREAD

**Issue by quickflash2** [mudkipme/MoeMemosAndroid#1]
Can you add the function of remembering the user name and password? It is inconvenient to enter each time. Thanks

**Comment by mudkipme** [comment]
The app uses [cookie](https://github.com/gotev/android-cookie-store) to store session key, which is the same login mechanism with Memos' web app. The login status should be kept as long as the server is not restarted.

Did you restarted the server before the app asks you to re-login? It might be a bug if the server didn't restart.

The reason the app (and Memos' web) asks re-login after a server restart is because Memos generate a random secure cookie key when server starts: https://github.com/usememos/memos/blob/main/server/server.go#L52
I'm considering to create a pull request to allow users set their own cookie key in environment variable.

**Comment by luckfu** [comment]
并没有重启服务器，这两天使用下来，发现这还是常态化的，也就是说在ios下，并没有上滑强制关闭app，隔几个小时后再打开，也可能需要重登录，ios16.02

**Comment by mudkipme** [comment]
To avoid having to re-login after session invalidation, an alternative login method: *login with Open API* will be added in future version. It will store the `openId` and doesn't use cookie.

**Comment by mudkipme** [comment]
Moe Memos v0.2.0 for Android is released with "Sign in with Open API" option. It will keep your login status even if the session is expired or the server restarted.
