### ISSUE TITLE
无法登录，invalid access token

### ISSUE THREAD

**Issue by cethink** [mudkipme/MoeMemosAndroid#89]
memos版本v0.13.2

**Comment by mudkipme** [comment]
Moe Memos uses `/api/status` to detect the version Memos.

It seems there is an issue fixed by https://github.com/usememos/memos/commit/2033b0c8fa8fe7c759949b7be28b289ca74b122a, which prevent `/api/status` from accessible in some conditions. As a result, it's recommended to only log in via Open API with Memos 0.13.2.

The future version of Memos will move lots of API to `/api/v1` prefix, including `/api/v1/status`, that will require an update for Moe Memos.

**Comment by xydche** [comment]
清空app数据可以登录一次

**Comment by mudkipme** [comment]
Please upgrade to Memos 0.14 and Moe Memos 0.7.0 to fix this issue.

For Memos 0.13.2 users, it's recommended to only login via Open API (and not upgrading Moe Memos).
