### ISSUE TITLE
Image previews not visible in Compose sheet

### ISSUE THREAD

**Issue by bmacphail** [mudkipme/MoeMemosAndroid#93]
Hi, I recently updated memos to 0.14 after the breaking API changes. I saw there was a new "local" storage backend, and switched it on in the admin settings. However, now I'm unable to attach images to memos from MoeMemos. 

Images seem to upload when selected, and become available on the memos host, but they don't get attached to the memo. I am using the latest version of MoeMemos.

I really appreciate the work you've put into the app by the way! It really is a great blend of design and functionality. If there is a way to show my appreciation in the form of a small monetary donation, please let me know (regardless of the status of this issue)!

**Comment by bmacphail** [comment]
Oh actually, the storage backend isn't the issue. I switched it back to `database`, and images still aren't appearing in the compose sheet. But as soon as I click send on the memo to post it, it looks like the image has attached correctly. 

I've included a screen recording with this reply to illustrate the issue.

https://github.com/mudkipme/MoeMemosAndroid/assets/12399661/e426d588-13b2-4f26-bdae-a19979e13f53

**Comment by mudkipme** [comment]
Memos 0.13.2 and later added authentication for attachments URLs, it was supported in Memo list but I forgot image preview in compose sheet. It will be fixed in next release.

I'd like to accept donation for this project in the future, as that will motivate me to continue working on it and explore more ideas. Thanks again for your kind words. ❤️
